package libraries.inlacou.com.imagegetter

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.os.Bundle
import android.provider.MediaStore
import android.util.Log
import libraries.inlacou.com.imagegetter.PermissionUtils.DEBUG_TAG

import java.io.File
import java.io.FileInputStream
import java.io.FileNotFoundException
import java.io.IOException

/**
 * Created by inlacou on 26/04/16.
 */
class ImageGetter(private val activity: Activity,
                  private val crop: Boolean = true,
                  private val circular: Boolean = true,
                  private val fixed: Boolean = true,
                  private val useCamera: Boolean = true,
                  private val useGallery: Boolean = true,
                  private val width: Int = 1,
                  private val height: Int = 1,
                  private val request_code_select_picture: Int,
                  private val request_code_crop: Int,
                  private val callbacks: Callbacks) {

	var uri: Uri? = null
	private var tag: String? = null

	fun start(tag: String, destroyPrevious: Boolean = false) {
		if(destroyPrevious) destroy()
		this.uri = ImageUtils.generateURI(activity)
		Log.d(DEBUG_TAG + ".start", "uri: " + uri)
		this.tag = tag
		checkExternalStoragePermission()
	}

	fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
		for (i in permissions.indices) {
			Log.d(DEBUG_TAG,  "$i onActivityResult($requestCode, ${permissions[i]}, ${grantResults[i]})")
			if (permissions[i].equals(PermissionUtils.Permission.externalStorage.permission, ignoreCase = true)) {
				if(useCamera) {
					checkCameraPermission(uri)
				}else{
					ImageUtils.openImageIntent(activity, useCamera, useGallery, request_code_select_picture, uri)
				}
			} else if (permissions[i].equals(PermissionUtils.Permission.camera.permission, ignoreCase = true)) {
				ImageUtils.openImageIntent(activity, useCamera, useGallery, request_code_select_picture, uri)
			}
		}
	}

	private fun checkExternalStoragePermission() {
		val aux = this.uri
		PermissionUtils.checkGetIfNotPermission(activity, PermissionUtils.Permission.externalStorage, {
			if (useCamera) {
				checkCameraPermission(aux)
			} else {
				ImageUtils.openImageIntent(activity, false, useGallery, request_code_select_picture, aux)
			}
		})
	}

	private fun checkCameraPermission(aux: Uri?) {
		PermissionUtils.checkGetIfNotPermission(activity,
				PermissionUtils.Permission.camera,
				{ ImageUtils.openImageIntent(activity, useCamera, useGallery, request_code_select_picture, aux) })
	}

	fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
		if (resultCode == Activity.RESULT_OK) {
			if (requestCode == request_code_select_picture) {
				val isCamera: Boolean = if (data == null) {
					true
				} else {
					MediaStore.ACTION_IMAGE_CAPTURE == data.action
				}

				val selectedImageUri: Uri?
				if (isCamera) {
					selectedImageUri = uri
				} else {
					selectedImageUri = data?.data ?: uri
					//Example content://com.android.providers.media.documents/document/image%3A51353
					//It's generated by the system, not me
					//So old uri is useless
					//Maybe this works:
					uri = selectedImageUri
					//I cant make it break when getting from gallery
				}

				/*Bitmap bitmap = ((BitmapDrawable) yourDrawable).getBitmap();

				Rotate the bitmap
				bitmap = ImageUtils.rotateBitmap(ImageUtils.getCameraPhotoOrientation(this, selectedImageUri), bitmap);

				selectedImage = ImageUtils.scaleBitmapKeepAspectRatio(bitmap, 250, 250);*/

				if (!crop) {
					callbacks.setImage(selectedImageUri.toString(), tag)
				} else {
					Log.d(DEBUG_TAG + ".onActivityResult", "launching CircularCropActivity intent")
					launchCropActivity(selectedImageUri)
				}
			} else if (requestCode == request_code_crop) {
				val filename = data!!.getStringExtra(CropActivity.RESPONSE_EXTRA_BITMAP)
				Log.d(DEBUG_TAG + ".onActivityResult", "3 - filename: " + filename)
				callbacks.setImage(filename, tag)
				uri = Uri.parse(filename)
			}
		} else if (resultCode == Activity.RESULT_CANCELED) {
			uri = null
			return
		}
	}

	private fun launchCropActivity(selectedImageUri: Uri?) {
		val intent = Intent(activity, CropActivity::class.java)
		intent.putExtra(CropActivity.INTENT_EXTRA_URI, selectedImageUri)
		intent.putExtra(CropActivity.INTENT_EXTRA_CIRCULAR, circular)
		intent.putExtra(CropActivity.INTENT_EXTRA_WIDTH, width)
		intent.putExtra(CropActivity.INTENT_EXTRA_HEIGHT, height)
		intent.putExtra(CropActivity.INTENT_EXTRA_FIXED, fixed)
		activity.startActivityForResult(intent, request_code_crop)
	}

	fun onSaveInstanceState(outState: Bundle) {
		if (uri != null) outState.putString("uri", uri!!.toString())
		outState.putBoolean("crop", crop)
		outState.putBoolean("circular", circular)
		outState.putBoolean("fixed", fixed)
		outState.putInt("width", width)
		outState.putInt("height", height)
		outState.putInt("request_code_select_picture", request_code_select_picture)
		outState.putInt("request_code_crop", request_code_crop)
		outState.putBoolean("use_camera", useCamera)
	}

	fun destroy() {
		Log.d(DEBUG_TAG + ".destroy", "deleteing... ")
		try {
			Log.d(DEBUG_TAG + ".destroy", "uri.getPath: " + uri!!.path)
			destroy(uri!!.path)
		} catch (npe: NullPointerException) {
			Log.d(DEBUG_TAG + ".destroy", "nothing!")
		}

	}

	fun destroy(path: String) {
		Log.d(DEBUG_TAG + ".destroy", "deleteing... ")
		try {
			Log.d(DEBUG_TAG + ".destroy", "received path: " + path)
			File(uri!!.path).delete()
		} catch (npe: NullPointerException) {
			Log.d(DEBUG_TAG + ".destroy", "nothing!")
		}

	}

	interface Callbacks {
		fun setImage(path: String, tag: String?)
	}

	companion object {
		private val DEBUG_TAG = ImageGetter::class.java.simpleName

		@Throws(IOException::class)
		fun getBitmapFromPath(context: Context, filename: String, size: Int): Bitmap {
			Log.d(DEBUG_TAG + ".getBitmapFromPath", "filename: " + filename)
			Log.d(DEBUG_TAG + ".getBitmapFromPath", "size: " + size)
			return try {
				val inputStream = FileInputStream(filename)
				var bitmap = BitmapFactory.decodeStream(inputStream)
				bitmap = ImageUtils.scaleBitmapKeepAspectRatio(bitmap, size)
				inputStream.close()
				bitmap
			} catch (fnfe: FileNotFoundException) {
				Log.d(DEBUG_TAG + ".getBitmapFromPath", "FileNotFoundException! Trying other approach...")
				ImageUtils.scaleBitmapKeepAspectRatio(MediaStore.Images.Media.getBitmap(
						context.contentResolver, Uri.parse(filename)), size)
			}

		}

		@Throws(IOException::class)
		fun getBitmapFromPath(filename: String): Bitmap {
			val inputStream = FileInputStream(filename)
			val bitmap = BitmapFactory.decodeStream(inputStream)
			inputStream.close()
			return bitmap
		}

		fun onRestoreInstanceState(savedInstanceState: Bundle, activity: Activity, callbacks: Callbacks): ImageGetter? {
			if (savedInstanceState.containsKey("crop") && savedInstanceState.containsKey("circular") && savedInstanceState.containsKey("uri")) {
				val imageGetter = ImageGetter(activity,
						crop = savedInstanceState.getBoolean("crop"),
						circular = savedInstanceState.getBoolean("circular"),
						fixed = savedInstanceState.getBoolean("fixed"),
						useCamera = savedInstanceState.getBoolean("use_camera"),
						width = savedInstanceState.getInt("width"),
						height = savedInstanceState.getInt("height"),
						request_code_select_picture = savedInstanceState.getInt("request_code_select_picture"),
						request_code_crop = savedInstanceState.getInt("request_code_crop"),
						callbacks = callbacks)
				imageGetter.uri = Uri.parse(savedInstanceState.getString("uri"))
				return imageGetter
			}
			return null
		}
	}

}
